spring:
  jwt:
    secret: "afsdlkdfavjnmoiasnfqwpqoiwjpoivsdjklsdafoiuanidvosadlkjldasfjtyrhpoiqwmaksfjobinbmasdmoon"

  datasource:
    url: jdbc:mysql://localhost:3306/travilitydb
    username: travilityuser
    password: travilityuser
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    oauth2:
      client:
        registration:
          naver:  # 네이버 OAuth2 설정
            client-name: naver
            client-id: V6M6t0E5IFYxF6Cwb_lc
            client-secret: n5gf2L_TbC
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
          google:  # 구글 OAuth2 설정 : 구글은 provider필요없음
            client-name: google
            client-id: 982270729134-9kmtoo0s06h0ad34ak764hn268rq2osp.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope:
              - profile
              - email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response


  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect


logging:
  level:
    root: INFO
    org.springframework.security: DEBUG

