spring:
  datasource:
    url: jdbc:mysql://localhost:3306/travility
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    oauth2:
      client:
        registration:
          naver:  # 네이버 OAuth2 설정
            client-name: naver
            client-id: {  }
            client-secret: {  }
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
          google:  # 구글 OAuth2 설정 : 구글은 provider필요없음
            client-name: google
            client-id: {  }
            client-secret: {  }
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope:
              - profile
              - email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  jwt:
    secret: "afsdlkdfavjnmoiasnfqwpqoiwjpoivsdjklsdafoiuanidvosadlkjldasfjtyrhpoiqwmaksfjobinbmasdmoon"


logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
