spring:
  jwt:
    secret: 15b86a423862e4744d84a72dfeaa1a8ed98619816f4002638383e402f99699cbb195bce322d41b11cb9b00e0886fbbff8c01e2eb10a06ed28ff3f3a50ed50e7b
  datasource:
    url: jdbc:mysql://localhost:3306/travility
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    oauth2:
      client:
        registration:
          naver:  # 네이버 OAuth2 설정
            client-name: naver
            client-id: V6M6t0E5IFYxF6Cwb_lc
            client-secret: n5gf2L_TbC
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
          google:  # 구글 OAuth2 설정 : 구글은 provider필요없음
            client-name: google
            client-id: 982270729134-9kmtoo0s06h0ad34ak764hn268rq2osp.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope:
              - profile
              - email
          kakao:  # 카카오 OAuth2 설정
            client-name: kakao
            client-id: 5a79d60fc080a20674f0a021c7a339a6
            client-secret: fRPT4wA24gyVnoBooJKVkdXt3nlpcxnh
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
              - account_email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect


logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
